# Generated by Django 5.1.11 on 2025-08-20 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Builder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SubAssembly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='BuildRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_minutes', models.FloatField()),
                ('build_date', models.DateField(auto_now_add=True)),
                ('builder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='builds', to='blog.builder')),
                ('subassembly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='builds', to='blog.subassembly')),
            ],
        ),
    ]
