# Generated by Django 5.1.11 on 2025-08-20 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_builder_subassembly_buildrecord'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
