# Generated by Django 5.1.11 on 2025-08-20 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_delete_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subassembly',
            options={'verbose_name': 'Sub Assembly', 'verbose_name_plural': 'Sub Assemblies'},
        ),
        migrations.AlterField(
            model_name='buildrecord',
            name='build_date',
            field=models.DateField(),
        ),
    ]
