# Generated by Django 5.1.11 on 2025-08-20 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_subassembly_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subassembly',
            name='description',
        ),
    ]
