# Generated by Django 5.1.11 on 2025-08-27 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_subassembly_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildrecord',
            name='signed_off_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
